[workspace]

members = [
    "http_server",
    "repository"
]

[workspace.dependencies]
uuid = { version = "1.4.1", features = ["v4", "serde"] }
serde_json = "1.0.104"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0.72"
